# Generated by Django 5.2.4 on 2025-07-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuchka', '0002_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
